name: Helm

on:
    push:
        branches:
            - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'tmf635-usage.name'
          namespace: 'default'
          chart: 'helm'
          helm: 'helm repo update'
          token: '${{ github.token }}'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'